[package]
name = "homography"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33", default-features = false, features = ["libm"] }

image = "0.25"
minifb = "0.27"
rqrr = "0.8.0"

[features]
rqrr = []
